//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuaBenhThuCung
    {
        public string MaDon { get; set; }
        public string TenThuCung { get; set; }
        public string ChungLoai { get; set; }
        public int CanNang { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public string TinhTrang { get; set; }
        public decimal PhiDieuTri { get; set; }
    }
}
