//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiThuCungEntities2 : DbContext
    {
        public QuanLiThuCungEntities2()
            : base("name=QuanLiThuCungEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChamSocHoThuCung> ChamSocHoThuCungs { get; set; }
        public virtual DbSet<ChuaBenhThuCung> ChuaBenhThuCungs { get; set; }
    }
}
